<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ユーザーデータの配列を定義
        $users = [
            [
                'name' => '田中太郎',
                'age' => 27,
                'grade' => '3年生',
                'faculty' => '工学部',
                'sex' => '男性',
                'self_introduction' => 'こんにちは、田中太郎です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/tanakataro',
                'twitter_link' => 'https://twitter.com/tanakataro',
                'instagram_link' => 'https://instagram.com/tanakataro',
                'registered_sns_flag' => '1',
                'email' => 'tanaka@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '山田花子',
                'age' => 24,
                'grade' => '2年生',
                'faculty' => '人文学部',
                'sex' => '女性',
                'self_introduction' => 'はじめまして、山田花子です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/yamadahanako',
                'twitter_link' => 'https://twitter.com/yamadahanako',
                'instagram_link' => 'https://instagram.com/yamadahanako',
                'registered_sns_flag' => '1',
                'email' => 'yamada@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '佐藤健太',
                'age' => 26,
                'grade' => '4年生',
                'faculty' => '法学部',
                'sex' => '男性',
                'self_introduction' => 'こんにちは、佐藤健太です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/satokensuke',
                'twitter_link' => 'https://twitter.com/satokensuke',
                'instagram_link' => 'https://instagram.com/satokensuke',
                'registered_sns_flag' => '1',
                'email' => 'sato@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '鈴木美咲',
                'age' => 23,
                'grade' => '1年生',
                'faculty' => '理学部',
                'sex' => '女性',
                'self_introduction' => 'はじめまして、鈴木美咲です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/suzukimisaki',
                'twitter_link' => 'https://twitter.com/suzukimisaki',
                'instagram_link' => 'https://instagram.com/suzukimisaki',
                'registered_sns_flag' => '1',
                'email' => 'suzuki@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '高橋雄一',
                'age' => 25,
                'grade' => '3年生',
                'faculty' => '経済科学部',
                'sex' => '男性',
                'self_introduction' => 'こんにちは、高橋雄一です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/takahashiyoichi',
                'twitter_link' => 'https://twitter.com/takahashiyoichi',
                'instagram_link' => 'https://instagram.com/takahashiyoichi',
                'registered_sns_flag' => '1',
                'email' => 'takahashi@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '伊藤理子',
                'age' => 24,
                'grade' => '2年生',
                'faculty' => '教育学部',
                'sex' => '女性',
                'self_introduction' => 'はじめまして、伊藤理子です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/itoriko',
                'twitter_link' => 'https://twitter.com/itoriko',
                'instagram_link' => 'https://instagram.com/itoriko',
                'registered_sns_flag' => '1',
                'email' => 'ito@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '小林大介',
                'age' => 26,
                'grade' => '4年生',
                'faculty' => '農学部',
                'sex' => '男性',
                'self_introduction' => 'こんにちは、小林大介です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/kobayashidaisuke',
                'twitter_link' => 'https://twitter.com/kobayashidaisuke',
                'instagram_link' => 'https://instagram.com/kobayashidaisuke',
                'registered_sns_flag' => '1',
                'email' => 'kobayashi@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '渡辺真理',
                'age' => 23,
                'grade' => '1年生',
                'faculty' => '経済科学部',
                'sex' => '女性',
                'self_introduction' => 'はじめまして、渡辺真理です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/watanabemari',
                'twitter_link' => 'https://twitter.com/watanabemari',
                'instagram_link' => 'https://instagram.com/watanabemari',
                'registered_sns_flag' => '1',
                'email' => 'watanabe@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '山本拓斗',
                'age' => 25,
                'grade' => '3年生',
                'faculty' => '経済科学部',
                'sex' => '男性',
                'self_introduction' => 'こんにちは、山本拓斗です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/yamamototakuto',
                'twitter_link' => 'https://twitter.com/yamamototakuto',
                'instagram_link' => 'https://instagram.com/yamamototakuto',
                'registered_sns_flag' => '1',
                'email' => 'yamamoto@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '中村真美',
                'age' => 24,
                'grade' => '2年生',
                'faculty' => '工学部',
                'sex' => '女性',
                'self_introduction' => 'はじめまして、中村真美です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/nakamuramami',
                'twitter_link' => 'https://twitter.com/nakamuramami',
                'instagram_link' => 'https://instagram.com/nakamuramami',
                'registered_sns_flag' => '1',
                'email' => 'nakamura@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '小川隆司',
                'age' => 26,
                'grade' => '4年生',
                'faculty' => '人文学部',
                'sex' => '男性',
                'self_introduction' => 'こんにちは、小川隆司です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/ogawatakashi',
                'twitter_link' => 'https://twitter.com/ogawatakashi',
                'instagram_link' => 'https://instagram.com/ogawatakashi',
                'registered_sns_flag' => '1',
                'email' => 'ogawa@example.com',
                'password' => Hash::make('11111111'),
            ],
            [
                'name' => '高田千尋',
                'age' => 23,
                'grade' => '1年生',
                'faculty' => '医学部医学科',
                'sex' => '女性',
                'self_introduction' => 'はじめまして、高田千尋です。',
                'avatar' => 'default-avatar.png',
                'line_link' => 'https://line.me/takatachihiro',
                'twitter_link' => 'https://twitter.com/takatachihiro',
                'instagram_link' => 'https://instagram.com/takatachihiro',
                'registered_sns_flag' => '1',
                'email' => 'takata@example.com',
                'password' => Hash::make('11111111'),
            ],
        ];

        // ユーザーデータをデータベースに挿入
        DB::table('users')->insert($users);
    }
}
